### ISSUE TITLE
Current format is deprecated

### ISSUE THREAD

**Issue by markgeraty** [VisionistInc/showdown-xss-filter#5]
`DEPRECATION WARNING: xssfilter is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!`

Need to update this extension to work with the new showdown extension loading methods.

**Comment by markgeraty** [comment]
@tivie The code for this extensions seems to still follow the format given in the wiki and in the other extensions ... what am I missing?

**Comment by tivie** [comment]
@markgeraty Sorry. I've updated the extension loading mechanism but had not the time to update the documentation. I will update the docs ASAP so third party extensions can catch up.

**Comment by markgeraty** [comment]
@tivie thanks for the update :)  and no need to apologize!  I just wanted to make sure that I was not missing something obvious.

I'll keep an eye on the showdown wiki.

**Comment by markgeraty** [comment]
@tivie hey so did the update to the extension loading mechanism happen?

**Comment by markgeraty** [comment]
@tivie nevermind - I found it in the release notes!
